FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /build

COPY pom.xml ./pom.xml
COPY api-gateway/pom.xml ./api-gateway/pom.xml

WORKDIR /build/api-gateway
RUN mvn dependency:go-offline -B

COPY api-gateway/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:25-jre-alpine
WORKDIR /api-gateway

COPY --from=builder /build/api-gateway/target/api-gat-0.0.1-SNAPSHOT.jar app.jar

ENV SPRING_PROFILES_ACTIVE=docker
CMD ["java", "-jar", "app.jar"]

