services:
  user-postgres:
    image: postgres:16
    container_name: user-service-postgres
    environment:
      POSTGRES_DB: ${USER_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${USER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_SERVICE_POSTGRES_USER} -d ${USER_SERVICE_POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  auth-postgres:
    image: postgres:16
    container_name: auth-service-postgres
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_SERVICE_POSTGRES_USER} -d ${AUTH_SERVICE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  order-postgres:
    image: postgres:16
    container_name: order-service-postgres
    environment:
      POSTGRES_DB: ${ORDER_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${ORDER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDER_SERVICE_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ORDER_SERVICE_POSTGRES_USER} -d ${ORDER_SERVICE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  user-liquibase:
    image: liquibase/liquibase:4.29
    container_name: liquibase_user_service_runner
    depends_on:
      user-postgres:
        condition: service_healthy
    volumes:
      - ./user-service/migrations:/liquibase/changelog
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://user-postgres:5432/${USER_SERVICE_POSTGRES_DB}
      LIQUIBASE_COMMAND_USERNAME: ${USER_SERVICE_POSTGRES_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/changelog.xml
    command: ["update"]
    networks:
      - backend

  order-liquibase:
    image: liquibase/liquibase:4.29
    container_name: liquibase_order_service_runner
    depends_on:
      order-postgres:
        condition: service_healthy
    volumes:
      - ./order-service/migrations:/liquibase/changelog
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://order-postgres:5432/${ORDER_SERVICE_POSTGRES_DB}
      LIQUIBASE_COMMAND_USERNAME: ${ORDER_SERVICE_POSTGRES_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${ORDER_SERVICE_POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/changelog.xml
    command: [ "update" ]
    networks:
      - backend

  auth-liquibase:
    image: liquibase/liquibase:4.29
    container_name: liquibase_auth_service_runner
    depends_on:
      auth-postgres:
        condition: service_healthy
    volumes:
      - ./authentication-service/migrations:/liquibase/changelog
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://auth-postgres:5432/${AUTH_SERVICE_POSTGRES_DB}
      LIQUIBASE_COMMAND_USERNAME: ${AUTH_SERVICE_POSTGRES_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/changelog.xml
    command: [ "update" ]
    networks:
      - backend

  redis:
    image: redis:7.4-alpine
    container_name: user-service-redis
    restart: unless-stopped
    command: redis-server --requirepass ${USER_SERVICE_REDIS_PASSWORD} --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${USER_SERVICE_REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  user-service:
    image: mkhalez/user-service:v1
    container_name: user-service
    depends_on:
      user-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-liquibase:
        condition: service_completed_successfully
      auth-service:
        condition: service_started
    restart: unless-stopped
    environment:
      POSTGRES_HOST: user-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${USER_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${USER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
      USER_SERVICE_REDIS_HOST: user-service-redis
      USER_SERVICE_REDIS_PORT: 6379
      USER_SERVICE_REDIS_PASSWORD: ${USER_SERVICE_REDIS_PASSWORD}
      AUTH_SERVICE_HOST: auth-service
      AUTH_PORT: 8080
      KAFKA_BROKER_HOST_1: kafka-broker-0
      KAFKA_BROKER_HOST_2: kafka-broker-1
      KAFKA_BROKER_HOST_3: kafka-broker-2
      KAFKA_BROKER_PORT_1: ${KAFKA_BROKER_PORT_0}
      KAFKA_BROKER_PORT_2: ${KAFKA_BROKER_PORT_1}
      KAFKA_BROKER_PORT_3: ${KAFKA_BROKER_PORT_2}
      SCHEMA_REGISTRY_HOST: schema-registry
      SCHEMA_REGISTRY_PORT: ${SCHEMA_REGISTRY_PORT}
      AUTH_HOST: auth-service
      SERVER_PORT: 8080
    networks:
      - backend

  payment-service:
    image: mkhalez/payment-service:v1
    container_name: payment-service
    depends_on:
      mongodb:
        condition: service_healthy
      mongo-liquibase:
        condition: service_completed_successfully
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
      AUTH_SERVICE_HOST: auth-service
      AUTH_PORT: 8080
      KAFKA_BROKER_HOST_1: kafka-broker-0
      KAFKA_BROKER_HOST_2: kafka-broker-1
      KAFKA_BROKER_HOST_3: kafka-broker-2
      KAFKA_BROKER_PORT_1: ${KAFKA_BROKER_PORT_0}
      KAFKA_BROKER_PORT_2: ${KAFKA_BROKER_PORT_1}
      KAFKA_BROKER_PORT_3: ${KAFKA_BROKER_PORT_2}
      SCHEMA_REGISTRY_HOST: schema-registry
      SCHEMA_REGISTRY_PORT: ${SCHEMA_REGISTRY_PORT}
      ORDER_SERVICE_HOST: order-service
      ORDER_SERVICE_PORT: 8080
      SERVER_PORT: 8080
      API_KEY: ${API_KEY}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_AUTH_SOURCE: ${MONGODB_AUTH_SOURCE}
      MONGODB_REPLICA_SET_NAME: rs0

    networks:
      - backend

  order-service:
    image: mkhalez/order-service:v1
    container_name: order-service
    depends_on:
      order-postgres:
        condition: service_healthy
      order-liquibase:
        condition: service_completed_successfully
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
    restart: unless-stopped
    environment:
      POSTGRES_HOST: order-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${ORDER_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${ORDER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDER_SERVICE_POSTGRES_PASSWORD}
      AUTH_SERVICE_HOST: auth-service
      AUTH_PORT: 8080
      KAFKA_BROKER_HOST_1: kafka-broker-0
      KAFKA_BROKER_HOST_2: kafka-broker-1
      KAFKA_BROKER_HOST_3: kafka-broker-2
      KAFKA_BROKER_PORT_1: ${KAFKA_BROKER_PORT_0}
      KAFKA_BROKER_PORT_2: ${KAFKA_BROKER_PORT_1}
      KAFKA_BROKER_PORT_3: ${KAFKA_BROKER_PORT_2}
      SCHEMA_REGISTRY_HOST: schema-registry
      SCHEMA_REGISTRY_PORT: ${SCHEMA_REGISTRY_PORT}
      AUTH_HOST: auth-service
      SERVER_PORT: 8080
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: 8080
    networks:
      - backend

  auth-service:
    image: mkhalez/authentication-service:v1
    container_name: auth-service
    depends_on:
      auth-postgres:
        condition: service_healthy
      auth-liquibase:
        condition: service_completed_successfully
    restart: unless-stopped
    environment:
      POSTGRES_HOST: auth-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
      KAFKA_BROKER_HOST_1: kafka-broker-0
      KAFKA_BROKER_HOST_2: kafka-broker-1
      KAFKA_BROKER_HOST_3: kafka-broker-2
      KAFKA_BROKER_PORT_1: ${KAFKA_BROKER_PORT_0}
      KAFKA_BROKER_PORT_2: ${KAFKA_BROKER_PORT_1}
      KAFKA_BROKER_PORT_3: ${KAFKA_BROKER_PORT_2}
      SCHEMA_REGISTRY_HOST: schema-registry
      SCHEMA_REGISTRY_PORT: ${SCHEMA_REGISTRY_PORT}
      AUTH_ADMIN_PASSWORD: ${AUTH_ADMIN_PASSWORD}
      AUTH_ADMIN_USERNAME: ${AUTH_ADMIN_USERNAME}
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: 8080
      SERVER_PORT: 8080
    networks:
      - backend

  api-gateway:
    image: mkhalez/api-gateway:v1
    container_name: api-gateway
    depends_on:
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      order-service:
        condition: service_started
      payment-service:
        condition: service_started
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      AUTH_SERVICE_URL: http://auth-service:8080
      USER_SERVICE_URL: http://user-service:8080
      ORDER_SERVICE_URL: http://order-service:8080
      PAYMENT_SERVICE_URL: http://payment-service:8080
      SERVER_PORT: 8080
    networks:
      - backend

  kafka-broker-0:
    image: confluentinc/cp-kafka:7.7.8
    container_name: kafka-broker-0
    hostname: kafka-broker-0
    environment:
      CLUSTER_ID: ZETVJENWRjaECDUEExP_eg
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9091,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-broker-0:9093,1@kafka-broker-1:9093,2@kafka-broker-2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-0:9091,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - backend


  kafka-broker-1:
    image: confluentinc/cp-kafka:7.7.8
    container_name: kafka-broker-1
    hostname: kafka-broker-1
    environment:
      CLUSTER_ID: ZETVJENWRjaECDUEExP_eg
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9091,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-broker-0:9093,1@kafka-broker-1:9093,2@kafka-broker-2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-1:9091,EXTERNAL://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - backend


  kafka-broker-2:
    image: confluentinc/cp-kafka:7.7.8
    container_name: kafka-broker-2
    hostname: kafka-broker-2
    environment:
      CLUSTER_ID: ZETVJENWRjaECDUEExP_eg
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9091,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-broker-0:9093,1@kafka-broker-1:9093,2@kafka-broker-2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-2:9091,EXTERNAL://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - backend


  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    hostname: kafka-ui
    depends_on:
      - kafka-broker-0
      - kafka-broker-1
      - kafka-broker-2
      - schema-registry
    ports:
      - "8086:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-0:9091,kafka-broker-1:9091,kafka-broker-2:9091
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    networks:
      - backend


  schema-registry:
    image: confluentinc/cp-schema-registry:8.2.0
    container_name: schema-registry
    hostname: schema-registry
    depends_on:
      - kafka-broker-0
      - kafka-broker-1
      - kafka-broker-2
    ports:
      - "${SCHEMA_REGISTRY_PORT}:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-broker-0:9091,kafka-broker-1:9091,kafka-broker-2:9091
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - backend

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    command: [ "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile" ]
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    healthcheck:
      test: >
        echo "try {
          rs.status()
        } catch (err) {
          rs.initiate({
            _id: 'rs0',
            members: [{ _id: 0, host: 'mongodb:27017' }]
          })
        }" | mongosh -u ${MONGODB_USER} -p ${MONGODB_PASSWORD} --authenticationDatabase admin --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend


  mongo-liquibase:
    image: liquibase/liquibase:4.29
    container_name: liquibase_payment_service_runner
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./payment-service/migrations:/liquibase/changelog
    environment:
      LIQUIBASE_COMMAND_URL: mongodb://mongodb:27017/${MONGODB_DB}?authSource=admin
      LIQUIBASE_COMMAND_USERNAME: ${MONGODB_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${MONGODB_PASSWORD}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/changelog.xml
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        curl -fsSL -o /liquibase/lib/liquibase-mongodb.jar \
          https://repo1.maven.org/maven2/org/liquibase/ext/liquibase-mongodb/4.29.2/liquibase-mongodb-4.29.2.jar && \
        curl -fsSL -o /liquibase/lib/mongodb-driver-sync.jar \
          https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-sync/5.2.0/mongodb-driver-sync-5.2.0.jar && \
        curl -fsSL -o /liquibase/lib/mongodb-driver-core.jar \
          https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-core/5.2.0/mongodb-driver-core-5.2.0.jar && \
        curl -fsSL -o /liquibase/lib/bson.jar \
          https://repo1.maven.org/maven2/org/mongodb/bson/5.2.0/bson-5.2.0.jar && \
        liquibase update
    networks:
      - backend


networks:
  backend:
    driver: bridge