spring:
  profiles:
    default: local
  application:
    name: api-gateway


app:
  permit-all-routes:
    - /api/auth/login
    - /api/auth/signup
  authenticated-routes:
    - /api/auth/**
    - /api/user/**
    - /api/order/**

server:
  port: 8083
