spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-refresh-route
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/refresh
              filters:
                - JwtClaimAuthorize=type,refresh

            - id: auth-route
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**

            - id: order-route
              uri: http://order-service:8082
              predicates:
                - Path=/api/order/**
              filters:
                - JwtClaimAuthorize=type,access

            - id: user-route
              uri: http://user-service:8080
              predicates:
                - Path=/api/user/**
              filters:
                - JwtClaimAuthorize=type,access