apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: microservices
type: Opaque
stringData:
  AUTH_SERVICE_POSTGRES_DB: auth-service
  AUTH_SERVICE_POSTGRES_USER: admin
  AUTH_SERVICE_POSTGRES_PASSWORD: password
  AUTH_ADMIN_PASSWORD: password
  AUTH_ADMIN_USERNAME: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: microservices
type: Opaque
stringData:
  ORDER_SERVICE_POSTGRES_DB: order-service
  ORDER_SERVICE_POSTGRES_USER: user
  ORDER_SERVICE_POSTGRES_PASSWORD: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: microservices
data:
  KAFKA_BROKER_PORT_0: "9091"
  KAFKA_BROKER_PORT_1: "9091"
  KAFKA_BROKER_PORT_2: "9091"
  SCHEMA_REGISTRY_PORT: "8081"
  CLUSTER_ID: "ZETVJENWRjaECDUEExP_eg"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: microservices
type: Opaque
stringData:
  API_KEY: cef3f2d2-d1e9-4a2a-9671-35cf2f5f102b
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DB: payment-service
  MONGODB_AUTH_SOURCE: admin
  MONGODB_REPLICA_SET_NAME: rs0
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: microservices
type: Opaque
stringData:
  USER_SERVICE_POSTGRES_DB: user-service
  USER_SERVICE_POSTGRES_USER: user
  USER_SERVICE_POSTGRES_PASSWORD: password
  USER_SERVICE_REDIS_PASSWORD: password