spring:
  profiles:
    default: local
  config:
    import: optional:file:payment-service/.env[.properties]
  application:
    name: payment-service

server:
  port: 8084

payment-creation:
  minutesDelta: 3

payment:
  sender:
    scheduler.fixed.delay: 5000
    max-attempts: 3
    limit: 10
    base-attempt-second: 2
    time-to-send-minutes: 2
