spring:
  profiles:
    default: local
  config:
    import: optional:file:payment-service/.env[.properties]
  application:
    name: payment-service

server:
  port: 8084

payment-creation:
  minutesDelta: 3

payment:
  sender:
    scheduler.fixed.delay: 5000
    max-attempts: 3
    limit: 10
    base-attempt-second: 2
    time-to-send-minutes: 2


kafka:
  topics:
    partitions: 3
    replicas: 3
    payment-operations-result-topic: payment-operations-result
    payment-operations-result-topic-dlq: payment-operations-result-dlq
    retry-policy:
      backoff:
        delay: 2000
        multiplier: 2
      attempts: 3