

user-service:
  base-url: http://localhost:8082/api/order
  connection-timeout: 3000
  read-timeout: 3000

bank-client:
  base-url: https://api.random.org/json-rpc/4/invoke
  connection-timeout: 3000
  read-timeout: 3000
  body:
    jsonrpc: 2.0
    method: generateIntegers
    id: 1
    params:
      n: 1
      min: 1
      max: 1000
      api-key: ${API_KEY}