spring:
  datasource:
    url: jdbc:postgresql://auth-postgres:5432/${POSTGRES_DOCKER_DB}
    username: ${POSTGRES_DOCKER_USER}
    password: ${POSTGRES_DOCKER_PASSWORD}

security:
  initial:
    admin-password: ${AUTH_ADMIN_PASSWORD}
    admin-username: ${AUTH_ADMIN_USERNAME}
    active: true
    roles:
      - admin
      - user

client:
  user-service:
    base-url: http://user-service:8080/api/user/register
    read-timeout: 2000
    connection-timeout: 2000