spring:
  config:
    import: optional:file:authentication-service/.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

security:
  initial:
    admin-password: ${ADMIN_PASSWORD}
    admin-username: ${ADMIN_USERNAME}
    active: true
    roles:
      - admin
      - user

client:
  user-service:
    base-url: http://localhost:8080/api/user/register
    read-timeout: 2000
    connection-timeout: 2000