spring:
  config:
    import: optional:file:order-service/.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5434/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

  kafka:
    bootstrap-servers:
      - localhost:29092
      - localhost:29093
      - localhost:29094
    consumer.properties:
      enable.auto.commit: false
      auto.offset.reset: earliest
      isolation.level: read_committed
      fetch.min.bytes: 16
      fetch.max.bytes: 1048576
      fetch.max.wait.ms: 10000
      max.poll.interval.ms: 50000
      max.poll.records: 10
      schema.registry.url: http://localhost:8087
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
      specific.avro.reader: true
      group.id: orderService

user-service:
  base-url: http://localhost:8080/api/user
  connection-timeout: 3000
  read-timeout: 3000

kafka:
  concurrent-listeners: 3
  auto-start: true
  payment-operations-result-topic: payment-operations-result