--liquibase formatted sql
--changeset mkh_alez:init-users-table

CREATE TABLE user_roles(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL references users(id),
    role_id int NOT NULL references roles(id),
    CONSTRAINT unique_pair UNIQUE(user_id, role_id)
);