--liquibase formatted sql
--changeset mkh_alez:init-users-table

CREATE TABLE user_roles(
    int id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NOT NULL references users(id),
    role_id NOT NULL references roles(id),
    CONSTRAINT unique_pair UNIQUE(user_id, role_id)
);