--liquibase formatted sql
--changeset mkh_alez:init-users-table

CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password text NOT NULL
);