FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /build

COPY pom.xml ./pom.xml
COPY user-service/pom.xml ./user-service/pom.xml

WORKDIR /build/user-service
RUN mvn dependency:go-offline -B

COPY user-service/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:25-jre-alpine
WORKDIR /user_service

COPY --from=builder /build/user-service/target/user-service-0.0.1-SNAPSHOT.jar app.jar

ENV SPRING_PROFILES_ACTIVE=docker
CMD ["java", "-jar", "app.jar"]

